"""Parity release gate: the declared experiment + validate(), import-safe.

This module is the single owner of the parity experiment (star set, mode
matrix, run constants), the gate thresholds, and `validate()`. The runner
(`run_parity.py`), the unit tests (`tests/unit/test_parity_gate.py`), and the
renderers (`make_report.py`, `make_parity_plots.py`) all import it, so every
consumer checks the SAME gate and none trusts the persisted `gate.passed`
boolean in the artifact (`validate_artifact` re-validates and cross-checks
the persisted gate block).

Import-safe on purpose: no machine-environment guard, no engine access. It
imports jwst_tool so the production worker version and the supported Pandeia
release are defined ONCE, in production code, not re-typed here.
"""
import re
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent          # tests/parity/scripts
sys.path.insert(0, str(_HERE.parents[2] / "src"))

from jwst_tool import instruments as _ins        # noqa: E402
from jwst_tool import noise as _noise            # noqa: E402

# ---------------------------------------------------------------------------
# The declared experiment. validate() requires the artifact to contain
# EXACTLY this matrix -- every star, one row per mode per star -- so a
# truncated artifact (a lost star, a dropped mode, a duplicated row) fails
# instead of quietly shrinking the claim.
# ---------------------------------------------------------------------------

# One transit's worth of time on each side of the transit (baseline
# fraction 1.0 in PandExo terms); WASP-39 b duration.
T_TRANSIT_S = 2.8036 * 3600.0
DEPTH = 0.01            # constant-depth planet (rp^2/r*^2)
SAT_LIMIT = 0.80

STARS = {
    "w39_like": dict(teff=5400.0, log_g=4.45, metallicity=0.0, ks_mag=10.663),
    "bright_hot": dict(teff=6250.0, log_g=4.30, metallicity=0.0, ks_mag=8.5),
    # a faint K dwarf so NIRSpec PRISM is UNSATURATED and gets a valid parity
    # point (it saturates on the two brighter stars -- there both tools flag
    # it and only the unusable-regime ngroup floor differs, ngroup 2 vs 1)
    "faint_k": dict(teff=4500.0, log_g=4.60, metallicity=0.0, ks_mag=13.0),
}

MODE_KEYS = ("nirspec_prism", "nirspec_g395h", "nirspec_g235h", "niriss_soss",
             "nircam_f322w2", "nircam_f444w", "miri_lrs")

# Modes that MUST produce a valid unsaturated comparison somewhere in the
# matrix; a silently missing row would otherwise shrink the claim.
REQUIRED_UNSATURATED_MODES = set(MODE_KEYS)

FAINT_STARS = {"faint_k"}

# The closed status vocabulary. A status the gate does not know is a row the
# gate cannot judge, so it is a FAILURE, not a skip (that hole once hid a
# 65.9%-pixel-match saturated PRISM row from every check).
VALID_STATUSES = {"OK", "ERROR", "SATURATED", "SATURATED_ABOVE_LIMIT"}

# ---------------------------------------------------------------------------
# Identity: defined once in production code, re-exported for the gate.
# ---------------------------------------------------------------------------

# The production worker version (src/jwst_tool/noise.py). A parity artifact
# generated by a different worker does not describe the code that ships.
PRODUCTION_WORKER_VERSION = _noise.WORKER_VERSION
# The supported Pandeia release; both sides must be on this exact triple.
REQUIRED_PANDEIA_RELEASE = _ins._SUPPORTED_PANDEIA_RELEASE
# PandExo is consumed from master, so the release artifact must be tied to the
# exact reviewed tree rather than merely recording whichever commit happened
# to be installed on the machine that ran the gate.
REQUIRED_PANDEXO_COMMIT = "34e42d81f782c8358bb30fc6e8cdf4b87e488263"

# ---------------------------------------------------------------------------
# Thresholds. Relaxing any of them belongs in the report with a reason,
# never in a silent edit to make a run go green.
# ---------------------------------------------------------------------------

# Wavelength match tolerance used by compare_mode in run_parity.py.
WL_MATCH_RTOL = 1e-9
# At least this fraction of ALL PandExo pixels must find an exact-wavelength
# partner on our side (the committed artifact measures 100% on every OK row).
MIN_MATCHED_PIXEL_FRAC = 0.99
# Group-count agreement. The faint rule passes on EITHER the absolute or the
# relative tolerance (whichever is looser), on purpose: at ngroup ~500-1000 a
# 5-group difference is ~1% and rounding to an integer is the only freedom
# left, so a pure 1% test fails on rounding alone (the 2026-07 artifact has
# 497-vs-492 = 1.006% and 195-vs-193 = 1.03%). REPORT.md states the same
# either/or rule.
MAX_NGROUP_ABS_DIFF = 1
MAX_NGROUP_REL_DIFF = 0.01
MAX_NGROUP_ABS_DIFF_FAINT = 5
# Extracted flux is a true 1:1 comparison (same engine, same configuration).
# This gates the MEDIAN ratio only; per-pixel extraction jitter (p05/p95 and
# max_abs_dev are recorded in every row) is a disclosed property of the two
# independent extractions, not a gated quantity.
MAX_FLUX_RATIO_DEV = 0.03

# NOTE: sigma ratios are REPORTED but deliberately NOT gated to unity. Pandeia's
# full extracted noise and PandExo's analytic `fml` estimator are different
# noise models on purpose; the measured envelope is ~2-24% (NIR) and ~33-56%
# (MIRI LRS). Requiring unity there would be requiring the two tools to stop
# disagreeing about something they disagree about by design.

# NOTE: PandExo operational warnings (e.g. the NIRCam data-volume excess under
# the pinned RAPID readout) are recorded per row (`pandexo_warnings`) and
# surfaced in REPORT.md, but they are NOT gate failures: this gate certifies
# numerical estimator parity at a fixed submitted configuration, not that the
# configuration is schedulable or operationally recommended.


def _release_of(version):
    """Leading dotted-numeric release segment ("2026.7.1" -> "2026.7")."""
    m = re.match(r"(\d+(?:\.\d+)*)", str(version or "").strip())
    return m.group(1) if m else None


def gate_thresholds() -> dict:
    """The thresholds block run_parity.py persists into the artifact."""
    return {
        "min_matched_pixel_frac": MIN_MATCHED_PIXEL_FRAC,
        "max_ngroup_abs_diff": MAX_NGROUP_ABS_DIFF,
        "max_ngroup_rel_diff": MAX_NGROUP_REL_DIFF,
        "max_flux_ratio_dev": MAX_FLUX_RATIO_DEV,
        "sat_limit": SAT_LIMIT,
        "wl_match_rtol": WL_MATCH_RTOL,
    }


def gate_block(problems: list[str]) -> dict:
    """The gate block run_parity.py writes into the artifact."""
    return {
        "passed": not problems,
        "problems": problems,
        "required_worker_version": PRODUCTION_WORKER_VERSION,
        "required_pandeia_release": REQUIRED_PANDEIA_RELEASE,
        "thresholds": gate_thresholds(),
    }


def validate(summary: dict) -> list[str]:
    """Return a list of gate failures; empty means the artifact is a PASS.

    Every check answers "would a reader of this artifact be misled?", not
    "did the code run?".
    """
    problems = []
    stars = summary.get("stars")
    if not isinstance(stars, dict) or not stars:
        return ["summary contains no stars"]

    # --- the artifact must contain the whole declared experiment ------------
    for sname in sorted(set(STARS) - set(stars)):
        problems.append(
            f"declared star {sname!r} is missing from the artifact; a "
            "truncated experiment cannot certify the full claim")
    for sname in sorted(set(stars) - set(STARS)):
        problems.append(
            f"artifact star {sname!r} is not part of the declared experiment")

    cfg = summary.get("config") or {}
    for name, want in (("transit_duration_s", T_TRANSIT_S), ("depth", DEPTH),
                       ("sat_limit", SAT_LIMIT), ("stars", STARS)):
        if cfg.get(name) != want:
            problems.append(
                f"artifact config {name}={cfg.get(name)!r} does not match the "
                f"declared experiment ({want!r})")

    for sname, star in stars.items():
        po = star.get("provenance_ours") or {}
        pp = star.get("provenance_pandexo") or {}

        # --- worker version -------------------------------------------------
        wv = po.get("worker_version")
        if wv != PRODUCTION_WORKER_VERSION:
            problems.append(
                f"{sname}: artifact worker_version={wv!r} but production runs "
                f"worker v{PRODUCTION_WORKER_VERSION}; this artifact does not "
                "describe the shipping code")

        # --- engine / refdata / PSF on BOTH sides ---------------------------
        ours_triple = {
            "engine": _release_of(po.get("engine_version")),
            "refdata": _release_of(po.get("refdata_version")),
            "psf": _release_of(po.get("psf_version")),
        }
        px_triple = {
            "engine": _release_of(pp.get("pandeia_engine_version")),
            "refdata": _release_of(pp.get("refdata_version")),
            "psf": _release_of(pp.get("psf_version")),
        }
        for comp in ("engine", "refdata", "psf"):
            a, b = ours_triple[comp], px_triple[comp]
            if a is None or b is None:
                problems.append(
                    f"{sname}: {comp} release unknown on "
                    f"{'our' if a is None else 'the PandExo'} side "
                    f"(ours={a!r}, pandexo={b!r}); an unattributable "
                    "comparison cannot gate a release")
            elif a != b:
                problems.append(
                    f"{sname}: {comp} release differs across the two sides "
                    f"(ours={a}, pandexo={b}); this compares two engines, not "
                    "two estimators")
            elif a != REQUIRED_PANDEIA_RELEASE:
                problems.append(
                    f"{sname}: {comp} release {a} is not the supported "
                    f"{REQUIRED_PANDEIA_RELEASE}")

        # --- PandExo identity -----------------------------------------------
        pandexo_commit = pp.get("pandexo_commit")
        if not pandexo_commit:
            problems.append(
                f"{sname}: PandExo git commit not recorded. PandExo is used "
                "from master, whose behavior moves without a version bump, so "
                "the version string alone does not identify what ran")
        elif pandexo_commit != REQUIRED_PANDEXO_COMMIT:
            problems.append(
                f"{sname}: PandExo commit {pandexo_commit!r} is not the "
                f"reviewed {REQUIRED_PANDEXO_COMMIT}; a different or dirty "
                "master tree cannot satisfy this release gate")
        if str(pp.get("pandexo_version", "unknown")).lower() in (
                "unknown", "none", ""):
            problems.append(
                f"{sname}: PandExo version is unknown in the provenance block")

        # --- the mode matrix: exactly one row per declared mode --------------
        rows = star.get("modes", [])
        keys = [row.get("key") for row in rows]
        for k in MODE_KEYS:
            n = keys.count(k)
            if n == 0:
                problems.append(f"{sname}: declared mode {k!r} has no row")
            elif n > 1:
                problems.append(f"{sname}: mode {k!r} appears {n} times; "
                                "duplicate rows cannot be attributed")
        for k in sorted({k for k in keys if k not in MODE_KEYS}):
            problems.append(
                f"{sname}: row key {k!r} is not part of the declared "
                "experiment")

        # --- per-mode rows ---------------------------------------------------
        for row in rows:
            key = row.get("key")
            tag = f"{sname}/{key}"
            status = row.get("status")

            if status not in VALID_STATUSES:
                problems.append(
                    f"{tag}: unknown status {status!r}; a status the gate "
                    "does not know is a row the gate cannot judge")
                continue
            if status == "ERROR":
                problems.append(
                    f"{tag}: error row "
                    f"(ours={row.get('ours_error', '')[:120]!r})")
                continue
            if status == "SATURATED":
                # the worker declared the configuration unusable; reported,
                # never a validation row (coverage handles the claim side)
                continue
            if status == "SATURATED_ABOVE_LIMIT":
                sat = row.get("sat_frac_ours")
                if sat is None or float(sat) <= SAT_LIMIT:
                    problems.append(
                        f"{tag}: labeled SATURATED_ABOVE_LIMIT but the "
                        f"measured sat_frac is {sat!r}; the label must come "
                        "from the measurement")
                continue

            # Saturation must be judged from the MEASURED fraction, not only
            # the worker's `unusable` flag. The committed 2026-07 artifact had
            # two OK rows above the limit, one at 7.31x full well.
            sat = row.get("sat_frac_ours")
            if sat is None:
                problems.append(f"{tag}: OK row with no measured sat_frac")
            elif float(sat) > SAT_LIMIT:
                problems.append(
                    f"{tag}: labeled OK with measured saturation "
                    f"{float(sat):.4f} above the {SAT_LIMIT} limit; a "
                    "saturated configuration may be reported but cannot "
                    "contribute a validation row")

            # pixel-grid identity
            npix_p, matched = row.get("npix_pandexo"), row.get("npix_matched")
            if not npix_p or matched is None:
                problems.append(f"{tag}: missing pixel-match counts")
            elif matched < MIN_MATCHED_PIXEL_FRAC * npix_p:
                problems.append(
                    f"{tag}: only {matched}/{npix_p} usable pixels matched at "
                    f"rtol {WL_MATCH_RTOL:g} "
                    f"(< {MIN_MATCHED_PIXEL_FRAC:.0%})")

            # Submitted instrument configuration must be identical. The one
            # reviewed representation exception is MIRI LRS: our registry
            # leaves its sole p750l disperser implicit while PandExo reports it.
            # A blanket "ignore whenever either side is None" rule would also
            # hide a genuinely missing subarray/readout/filter on every mode.
            co, cp = row.get("config_ours") or {}, row.get("config_pandexo") or {}
            for field in ("subarray", "readout", "filter", "disperser"):
                a, b = co.get(field), cp.get(field)
                implicit_miri_disperser = (
                    key == "miri_lrs" and field == "disperser"
                    and a is None and b == "p750l")
                if not implicit_miri_disperser and a != b:
                    problems.append(
                        f"{tag}: submitted {field} differs "
                        f"(ours={a!r}, pandexo={b!r})")

            # group counts (see the threshold comments for the either/or rule)
            go, gp = row.get("ngroup_ours"), row.get("ngroup_pandexo")
            if go is None or gp is None:
                problems.append(f"{tag}: missing ngroup on one side")
            elif sname in FAINT_STARS:
                diff = abs(go - gp)
                if (diff > MAX_NGROUP_ABS_DIFF_FAINT
                        and diff > MAX_NGROUP_REL_DIFF * max(go, gp)):
                    problems.append(
                        f"{tag}: ngroup {go} vs {gp} differs by {diff}, beyond "
                        f"both {MAX_NGROUP_ABS_DIFF_FAINT} groups absolute and "
                        f"{MAX_NGROUP_REL_DIFF:.0%} relative")
            elif abs(go - gp) > MAX_NGROUP_ABS_DIFF:
                problems.append(
                    f"{tag}: ngroup {go} vs {gp} differs by more than "
                    f"{MAX_NGROUP_ABS_DIFF}")

            # extracted flux (median-gated; see the threshold comment)
            fr = row.get("flux_ratio") or {}
            dev = fr.get("max_abs_dev")
            med = fr.get("median")
            if med is None:
                problems.append(f"{tag}: no extracted-flux ratio recorded")
            elif abs(med - 1.0) > MAX_FLUX_RATIO_DEV:
                problems.append(
                    f"{tag}: extracted-flux median ratio {med:.4f} is more "
                    f"than {MAX_FLUX_RATIO_DEV:.0%} from unity "
                    f"(max|dev| {dev})")

    # --- coverage: every mode needs at least one valid unsaturated row -------
    validated = {
        row.get("key")
        for star in stars.values()
        for row in star.get("modes", [])
        if row.get("status") == "OK"
        and row.get("sat_frac_ours") is not None
        and float(row["sat_frac_ours"]) <= SAT_LIMIT
    }
    missing = sorted(REQUIRED_UNSATURATED_MODES - validated)
    if missing:
        problems.append(
            "no valid unsaturated comparison for: " + ", ".join(missing)
            + " -- the artifact does not cover the modes it claims to")

    return problems


def validate_artifact(summary: dict) -> list[str]:
    """validate() plus cross-checks of the PERSISTED gate block.

    The renderers call this instead of trusting `gate.passed`: a hand-edited
    boolean, a stale thresholds block, or a gate written by different
    constants all fail here.
    """
    problems = list(validate(summary))
    gate = summary.get("gate")
    if not isinstance(gate, dict):
        problems.append(
            "artifact has no gate block (it predates the fail-closed gate); "
            "regenerate with run_parity.py")
        return problems
    if bool(gate.get("passed")) != (not problems):
        problems.append(
            "persisted gate.passed does not match a fresh validate(); the "
            "artifact was edited after the run or the gate has changed -- "
            "regenerate with run_parity.py")
    if gate.get("problems"):
        problems.append(
            f"persisted gate block records {len(gate['problems'])} "
            "problem(s); a failing artifact is not a certificate")
    expect = gate_block([])
    for k in ("required_worker_version", "required_pandeia_release",
              "thresholds"):
        if gate.get(k) != expect[k]:
            problems.append(
                f"persisted gate {k}={gate.get(k)!r} does not match the "
                f"current gate ({expect[k]!r}); regenerate the artifact")
    return problems
