"""The PandExo parity harness must FAIL CLOSED.

`run_parity.py` used to write a summary and exit 0 no matter what, so stale
or saturated artifacts looked like passing release gates. The gate now lives
in the import-safe `tests/parity/scripts/parity_gate.py`, shared by the
runner, the renderers, and these tests -- no exec tricks, no duplicated
constants. Each test breaks one thing in a synthetic full-matrix passing
summary and proves `validate()` (or `validate_artifact()`) fails; the last
tests require the COMMITTED artifact to re-validate as a current pass.
"""
from __future__ import annotations

import copy
import importlib
import sys
from pathlib import Path

import pytest

SCRIPTS = Path(__file__).resolve().parents[1] / "parity" / "scripts"
PLOTS = SCRIPTS / "make_parity_plots.py"


@pytest.fixture(scope="module")
def gate():
    """The shared gate module (parity_gate.py), imported -- never exec'd."""
    sys.path.insert(0, str(SCRIPTS))
    return vars(importlib.import_module("parity_gate"))


@pytest.fixture(scope="module")
def plots():
    """Load plotting guards without rendering a figure."""
    import importlib.util

    spec = importlib.util.spec_from_file_location("parity_plots_probe", PLOTS)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _ok_row(key, ngroup=100, sat=0.5):
    return {
        "key": key, "status": "OK",
        "sat_frac_ours": sat,
        "npix_pandexo": 1000, "npix_matched": 1000,
        "ngroup_ours": ngroup, "ngroup_pandexo": ngroup,
        "t_int_ours_s": 100.0, "t_int_pandexo_s": 100.0,
        "sigma_ratio_matched": {"median": 1.10},
        "config_ours": {"subarray": "sub", "readout": "RAPID",
                        "filter": "f", "disperser": "d"},
        "config_pandexo": {"subarray": "sub", "readout": "RAPID",
                           "filter": "f", "disperser": "d"},
        "flux_ratio": {"median": 1.001, "max_abs_dev": 0.02},
        "saturation_mask": {
            "n_ours": 1000, "n_pandexo": 1000, "n_matched": 1000,
            "matched_frac": 1.0, "partial_equal_frac": 1.0,
            "full_equal_frac": 1.0, "partial_disagree": 0,
            "full_disagree": 0,
        },
    }


@pytest.fixture
def passing(gate):
    """A full-matrix summary that satisfies every gate check."""
    rel = gate["REQUIRED_PANDEIA_RELEASE"]

    def star_block():
        return {
            "provenance_ours": {
                "worker_version": gate["PRODUCTION_WORKER_VERSION"],
                "engine_version": rel, "refdata_version": rel,
                "psf_version": rel,
            },
            "provenance_pandexo": {
                "pandeia_engine_version": rel, "refdata_version": rel,
                "psf_version": rel, "pandexo_version": "2026.7",
                "pandexo_commit": gate["REQUIRED_PANDEXO_COMMIT"],
            },
            # sorted(): REQUIRED_UNSATURATED_MODES is a set; unsorted
            # iteration made 4 tests hash-seed-flaky (which mode lands at
            # index 0 varies).
            "modes": [_ok_row(k)
                      for k in sorted(gate["REQUIRED_UNSATURATED_MODES"])],
        }

    return {
        "stars": {name: star_block() for name in gate["STARS"]},
        "config": {
            "transit_duration_s": gate["T_TRANSIT_S"],
            "depth": gate["DEPTH"],
            "sat_limit": gate["SAT_LIMIT"],
            "stars": copy.deepcopy(gate["STARS"]),
        },
    }


def test_a_clean_artifact_passes(gate, passing):
    assert gate["validate"](passing) == []


def test_worker_version_drift_fails(gate, passing):
    """A summary generated by a stale worker version must fail."""
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["provenance_ours"]["worker_version"] = 5
    problems = gate["validate"](s)
    assert any("worker_version=5" in p for p in problems), problems


def test_missing_saturation_mask_evidence_fails(gate, passing):
    s = copy.deepcopy(passing)
    del s["stars"]["w39_like"]["modes"][0]["saturation_mask"]
    problems = gate["validate"](s)
    assert any("saturation grids matched fraction" in p for p in problems), problems


def test_per_pixel_saturation_mask_disagreement_fails(gate, passing):
    s = copy.deepcopy(passing)
    mask = s["stars"]["w39_like"]["modes"][0]["saturation_mask"]
    mask["full_equal_frac"] = 0.999
    mask["full_disagree"] = 1
    problems = gate["validate"](s)
    assert any("full-saturation mask agreement" in p for p in problems), problems


def test_psf_version_mismatch_fails(gate, passing):
    """A mixed PSF release changes the PSF and so the extracted flux."""
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["provenance_pandexo"]["psf_version"] = "2026.2"
    problems = gate["validate"](s)
    assert any("psf release differs" in p for p in problems), problems


def test_unsupported_release_fails_even_when_both_sides_agree(gate, passing):
    """Two sides can agree with each other and still both be archival."""
    s = copy.deepcopy(passing)
    for side, keys in (("provenance_ours",
                        ("engine_version", "refdata_version", "psf_version")),
                       ("provenance_pandexo",
                        ("pandeia_engine_version", "refdata_version",
                         "psf_version"))):
        for k in keys:
            s["stars"]["w39_like"][side][k] = "2026.2"
    problems = gate["validate"](s)
    assert any("not the supported" in p for p in problems), problems


def test_missing_pandexo_commit_fails(gate, passing):
    """PandExo runs from master; a version string does not identify it."""
    s = copy.deepcopy(passing)
    del s["stars"]["w39_like"]["provenance_pandexo"]["pandexo_commit"]
    problems = gate["validate"](s)
    assert any("PandExo git commit" in p for p in problems), problems


@pytest.mark.parametrize("commit", ["0" * 40,
                                     "34e42d81f782c8358bb30fc6e8cdf4b87e488263-dirty"])
def test_unreviewed_or_dirty_pandexo_commit_fails(gate, passing, commit):
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["provenance_pandexo"]["pandexo_commit"] = commit
    problems = gate["validate"](s)
    assert any("is not the reviewed" in p for p in problems), problems


def test_unknown_pandexo_version_fails(gate, passing):
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["provenance_pandexo"]["pandexo_version"] = "unknown"
    problems = gate["validate"](s)
    assert any("PandExo version is unknown" in p for p in problems), problems


def test_saturated_row_labeled_ok_fails(gate, passing):
    """The old artifact carried two of these, one at 7.31x full well."""
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["modes"][0]["sat_frac_ours"] = 0.8548803964
    problems = gate["validate"](s)
    assert any("above the" in p and "limit" in p for p in problems), problems

    s["stars"]["w39_like"]["modes"][0]["sat_frac_ours"] = 7.3110978
    assert any("7.3111" in p for p in gate["validate"](s))


def test_error_row_fails(gate, passing):
    s = copy.deepcopy(passing)
    row = s["stars"]["w39_like"]["modes"][0]
    key = row["key"]
    s["stars"]["w39_like"]["modes"][0] = {
        "key": key, "status": "ERROR", "ours_error": "boom"}
    problems = gate["validate"](s)
    assert any("error row" in p for p in problems), problems


def test_missing_required_mode_fails(gate, passing):
    """One star losing a mode fails the matrix even though the coverage set
    is still satisfied by the other stars."""
    s = copy.deepcopy(passing)
    dropped = s["stars"]["w39_like"]["modes"].pop()
    problems = gate["validate"](s)
    assert any(f"declared mode {dropped['key']!r} has no row" in p
               for p in problems), problems


def test_missing_star_fails(gate, passing):
    """Deleting a whole star must fail: the reviewer demonstrated the old
    coverage-only check passed with two of three stars removed."""
    s = copy.deepcopy(passing)
    del s["stars"]["bright_hot"]
    del s["stars"]["faint_k"]
    problems = gate["validate"](s)
    assert any("missing from the artifact" in p for p in problems), problems


def test_undeclared_star_fails(gate, passing):
    s = copy.deepcopy(passing)
    s["stars"]["mystery"] = copy.deepcopy(s["stars"]["w39_like"])
    problems = gate["validate"](s)
    assert any("not part of the declared experiment" in p
               for p in problems), problems


def test_duplicate_row_fails(gate, passing):
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["modes"].append(
        copy.deepcopy(s["stars"]["w39_like"]["modes"][0]))
    problems = gate["validate"](s)
    assert any("appears 2 times" in p for p in problems), problems


def test_undeclared_mode_key_fails(gate, passing):
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["modes"].append(_ok_row("nirspec_g140h"))
    problems = gate["validate"](s)
    assert any("'nirspec_g140h' is not part of the declared" in p
               for p in problems), problems


def test_unknown_status_fails_instead_of_skipping(gate, passing):
    """The old validator silently skipped any non-OK/ERROR status; that hole
    hid a 65.9%-pixel-match row behind SATURATED_ABOVE_LIMIT."""
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["modes"][0]["status"] = "SATURATED_ISH"
    problems = gate["validate"](s)
    assert any("unknown status" in p for p in problems), problems


def test_saturated_above_limit_label_must_match_measurement(gate, passing):
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["modes"][0]["status"] = "SATURATED_ABOVE_LIMIT"
    # sat_frac is still 0.5, BELOW the limit -> mislabeled
    problems = gate["validate"](s)
    assert any("label must come from the measurement" in p
               for p in problems), problems


def test_config_block_drift_fails(gate, passing):
    s = copy.deepcopy(passing)
    s["config"]["depth"] = 0.02
    problems = gate["validate"](s)
    assert any("does not match the declared experiment" in p
               for p in problems), problems


def test_pixel_grid_mismatch_fails(gate, passing):
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["modes"][0]["npix_matched"] = 900     # 90%
    problems = gate["validate"](s)
    assert any("usable pixels matched" in p for p in problems), problems


def test_flux_ratio_drift_fails(gate, passing):
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["modes"][0]["flux_ratio"]["median"] = 1.05
    problems = gate["validate"](s)
    assert any("extracted-flux median ratio" in p for p in problems), problems


def test_config_mismatch_fails_but_miri_implicit_disperser_does_not(gate,
                                                                    passing):
    """A real disagreement fails; MIRI LRS's engine-derived disperser (ours
    unset, PandExo "p750l") is a representation difference and does not."""
    s = copy.deepcopy(passing)
    row = next(r for r in s["stars"]["w39_like"]["modes"]
               if r["key"] == "miri_lrs")
    row["config_ours"]["disperser"] = None
    row["config_pandexo"]["disperser"] = "p750l"
    assert not [p for p in gate["validate"](s) if "disperser" in p]

    row["config_ours"]["readout"] = "FASTR1"
    problems = gate["validate"](s)
    assert any("submitted readout differs" in p for p in problems), problems


@pytest.mark.parametrize("field", ["subarray", "readout", "filter",
                                    "disperser"])
def test_missing_config_value_fails_outside_exact_miri_exception(gate, passing,
                                                                 field):
    s = copy.deepcopy(passing)
    # pick a NON-miri row: the exception only covers miri_lrs's disperser
    row = next(r for r in s["stars"]["w39_like"]["modes"]
               if r["key"] != "miri_lrs")
    row["config_ours"][field] = None
    problems = gate["validate"](s)
    assert any(f"submitted {field} differs" in p for p in problems), problems


def test_faint_star_group_rounding_is_allowed(gate, passing):
    """At ngroup ~500 a 5-group rounding difference is 1.006%, so a pure 1%
    gate would fail the real, matched artifact."""
    s = copy.deepcopy(passing)
    star = s["stars"]["faint_k"]
    star["modes"][0].update(ngroup_ours=497, ngroup_pandexo=492)   # 1.006%
    star["modes"][1].update(ngroup_ours=195, ngroup_pandexo=193)   # 1.03%
    assert not [p for p in gate["validate"](s) if "ngroup" in p]

    # a real optimizer divergence still fails
    star["modes"][2].update(ngroup_ours=500, ngroup_pandexo=400)
    assert any("ngroup" in p for p in gate["validate"](s))


def test_bright_star_group_difference_of_two_fails(gate, passing):
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["modes"][0].update(ngroup_ours=20,
                                              ngroup_pandexo=18)
    problems = gate["validate"](s)
    assert any("ngroup 20 vs 18" in p for p in problems), problems


def test_validate_artifact_rejects_a_forged_passed_bit(gate, passing):
    """The renderers call validate_artifact(); a hand-edited artifact whose
    gate block says PASS must still be refused."""
    s = copy.deepcopy(passing)
    s["gate"] = gate["gate_block"]([])
    assert gate["validate_artifact"](s) == []

    broken = copy.deepcopy(s)
    del broken["stars"]["faint_k"]              # break it, keep "passed": true
    problems = gate["validate_artifact"](broken)
    assert any("does not match a fresh validate" in p for p in problems), \
        problems


def test_validate_artifact_rejects_tampered_thresholds(gate, passing):
    s = copy.deepcopy(passing)
    s["gate"] = gate["gate_block"]([])
    s["gate"]["thresholds"]["max_flux_ratio_dev"] = 0.5
    problems = gate["validate_artifact"](s)
    assert any("does not match the current gate" in p for p in problems), \
        problems


def test_validate_artifact_requires_a_gate_block(gate, passing):
    problems = gate["validate_artifact"](copy.deepcopy(passing))
    assert any("no gate block" in p for p in problems), problems


def test_gate_identity_is_single_sourced(gate):
    """Worker version and supported release come from production code and the
    deploy pin -- typed once, cross-checked here so they cannot drift."""
    from jwst_tool import instruments as ins
    from jwst_tool import noise

    assert gate["PRODUCTION_WORKER_VERSION"] == noise.WORKER_VERSION
    assert gate["REQUIRED_PANDEIA_RELEASE"] == ins._SUPPORTED_PANDEIA_RELEASE
    req = (Path(__file__).resolve().parents[2] / "deploy"
           / "requirements-pandeia.txt").read_text()
    assert f"pandeia.engine=={ins._SUPPORTED_PANDEIA_RELEASE}" in req, (
        "deploy/requirements-pandeia.txt does not pin the supported release")


def test_committed_artifact_passes_the_gate_on_the_supported_release(gate):
    """The committed artifact must BE a current pass, and stay one.

    validate_artifact() on what is committed must come back clean: fresh
    validation AND the persisted gate block agreeing with today's constants.
    A backend bump that lands without a fresh parity run fails here.
    """
    import json

    path = (SCRIPTS.parents[1] / "parity" / "outputs"
            / "parity_summary.json")
    if not path.is_file():                              # pragma: no cover
        pytest.skip("committed parity_summary.json not present")
    summary = json.loads(path.read_text())

    problems = gate["validate_artifact"](summary)
    assert not problems, f"the committed artifact no longer passes: {problems}"

    # the two sides name the engine field differently ("engine_version" ours,
    # "pandeia_engine_version" PandExo's); both record all three releases
    want = gate["REQUIRED_PANDEIA_RELEASE"]
    for sname, star in summary["stars"].items():
        for side, engine_key in (("provenance_ours", "engine_version"),
                                 ("provenance_pandexo",
                                  "pandeia_engine_version")):
            prov = star[side]
            for field in (engine_key, "refdata_version", "psf_version"):
                assert str(prov.get(field)) == want, (
                    f"{sname}/{side}: {field}={prov.get(field)!r} is not the "
                    f"supported {want}")


def test_committed_artifact_has_no_machine_paths(gate):
    """Provenance identity is names/releases/hashes, never workstation
    layout: run_parity scrubs absolute paths before writing the summary."""
    path = (SCRIPTS.parents[1] / "parity" / "outputs"
            / "parity_summary.json")
    if not path.is_file():                              # pragma: no cover
        pytest.skip("committed parity_summary.json not present")
    text = path.read_text()
    assert "/Users/" not in text and "/opt/" not in text and \
        "/home/" not in text, "machine-absolute paths leaked into the artifact"


def test_plots_refuse_a_summary_without_a_gate_block(plots):
    with pytest.raises(RuntimeError, match="no gate block"):
        plots.require_passing_summary({"stars": {}})


def test_plots_revalidate_instead_of_trusting_the_passed_bit(plots, gate,
                                                             passing):
    s = copy.deepcopy(passing)
    s["gate"] = gate["gate_block"]([])
    del s["stars"]["faint_k"]              # break it, keep "passed": true
    with pytest.raises(RuntimeError, match="failed its gate"):
        plots.require_passing_summary(s)


def test_plots_accept_a_revalidated_pass(plots, gate, passing):
    s = copy.deepcopy(passing)
    s["gate"] = gate["gate_block"]([])
    assert plots.require_passing_summary(s) == \
        gate["REQUIRED_PANDEIA_RELEASE"]


# --- 2026-08-09 review gates: short ramps, timing, sigma anomaly -------------

def test_short_ramp_group_mismatch_fails(gate, passing):
    """1 vs 2 groups is a ramp-policy divergence, not rounding: whenever
    either side is at or below LOW_NGROUP_EXACT the counts must be equal.
    This is the committed bright_hot/niriss_soss regression."""
    s = copy.deepcopy(passing)
    s["stars"]["bright_hot"]["modes"][0].update(
        ngroup_ours=1, ngroup_pandexo=2)
    problems = gate["validate"](s)
    assert any("short ramp" in p for p in problems), problems


def test_short_ramp_exact_agreement_passes(gate, passing):
    s = copy.deepcopy(passing)
    s["stars"]["bright_hot"]["modes"][0].update(
        ngroup_ours=2, ngroup_pandexo=2)
    assert gate["validate"](s) == []


def test_integration_time_gap_fails(gate, passing):
    """A 33% per-integration-time gap must fail even if the group diff
    passes its own tolerance."""
    s = copy.deepcopy(passing)
    s["stars"]["bright_hot"]["modes"][0].update(
        t_int_ours_s=11.008, t_int_pandexo_s=16.482)
    problems = gate["validate"](s)
    assert any("per-integration time" in p for p in problems), problems


def test_sigma_ratio_anomaly_fails(gate, passing):
    """The documented noise-model envelope tops out well under 2x; a 7x
    median sigma ratio is an anomaly and must fail, not pass as a
    'noise-model difference'."""
    s = copy.deepcopy(passing)
    s["stars"]["bright_hot"]["modes"][0]["sigma_ratio_matched"] = {
        "median": 7.08}
    problems = gate["validate"](s)
    assert any("anomaly band" in p for p in problems), problems


# --- review round 2: no fail-open paths --------------------------------------

def test_ok_row_missing_timing_fails(gate, passing):
    """An OK row without per-integration times must FAIL, not skip the
    timing gate."""
    s = copy.deepcopy(passing)
    del s["stars"]["w39_like"]["modes"][0]["t_int_ours_s"]
    problems = gate["validate"](s)
    assert any("timing gate cannot run" in p for p in problems), problems


def test_ok_row_missing_sigma_median_fails(gate, passing):
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["modes"][0]["sigma_ratio_matched"] = {}
    problems = gate["validate"](s)
    assert any("anomaly gate cannot run" in p for p in problems), problems


def _saturated_row(key, fw="% full well>80% (360% > 80%)"):
    return {"key": key, "status": "SATURATED",
            "ours_reason": "no unsaturated pixels at the shortest ramp",
            "ngroup_ours": 1, "sat_frac_ours": 3.56,
            "ngroup_pandexo": 1,
            "pandexo_warnings": {"% full well high?": fw},
            "saturation_mask": {
                "n_ours": 1000, "n_pandexo": 1000, "n_matched": 1000,
                "matched_frac": 1.0, "partial_equal_frac": 1.0,
                "full_equal_frac": 1.0, "partial_disagree": 0,
                "full_disagree": 0,
            }}


def test_saturated_row_claims_are_gated(gate, passing):
    """A SATURATED row must carry the measured fraction and PandExo's
    full-well verdict; a PandExo 'All good' on the same configuration is a
    saturation-status disagreement."""
    s = copy.deepcopy(passing)
    key = s["stars"]["bright_hot"]["modes"][0]["key"]
    s["stars"]["bright_hot"]["modes"][0] = _saturated_row(key)
    assert gate["validate"](s) == []          # honest saturated row passes

    s2 = copy.deepcopy(passing)
    row = _saturated_row(key, fw="All good (42% < 80%)")
    s2["stars"]["bright_hot"]["modes"][0] = row
    problems = gate["validate"](s2)
    assert any("saturation-status disagreement" in p for p in problems), problems

    s3 = copy.deepcopy(passing)
    row = _saturated_row(key)
    del row["pandexo_warnings"]
    s3["stars"]["bright_hot"]["modes"][0] = row
    problems = gate["validate"](s3)
    assert any("no PandExo full-well verdict" in p for p in problems), problems

    s4 = copy.deepcopy(passing)
    row = _saturated_row(key)
    row["sat_frac_ours"] = 0.5                 # claim without measurement
    s4["stars"]["bright_hot"]["modes"][0] = row
    problems = gate["validate"](s4)
    assert any("must come from the measurement" in p for p in problems), problems


def test_saturated_row_short_ramp_floor_mismatch_fails(gate, passing):
    s = copy.deepcopy(passing)
    key = s["stars"]["bright_hot"]["modes"][0]["key"]
    row = _saturated_row(key)
    row["ngroup_pandexo"] = 2                  # different floors saturated
    s["stars"]["bright_hot"]["modes"][0] = row
    problems = gate["validate"](s)
    assert any("floors the two tools saturate at" in p for p in problems), \
        problems
