"""The PandExo parity harness must FAIL CLOSED.

`run_parity.py` used to write a summary and exit 0 no matter what, so every
artifact it produced looked like a passing release gate -- including the
committed 2026-07 one, which was generated by worker v5 on Pandeia 2026.2, has
`pandexo_version: "unknown"` in two of three provenance blocks, and labels two
saturated NIRSpec PRISM rows `OK` (one at 7.31x full well).

These tests drive `validate()` with a synthetic PASSING summary and then break
one thing at a time, which is the acceptance criterion for change 4: deliberately
change worker version, PSF version, PandExo commit, or a row's saturation
fraction and prove the gate fails.

`run_parity.py` refuses to import without five machine-specific env vars set
(by design -- paths stay out of git), so the module is loaded here with those
vars stubbed and the tool imports skipped. Only `validate()` and the constants
are exercised; nothing runs an engine.
"""
from __future__ import annotations

import copy
from pathlib import Path

import pytest

PARITY = (Path(__file__).resolve().parents[1] / "parity" / "scripts"
          / "run_parity.py")


@pytest.fixture(scope="module")
def gate():
    """`validate` + constants from run_parity.py, without its env preamble."""
    import numpy as np

    src = PARITY.read_text()
    head, _, _ = src.partition("def main():")
    keep, skip = [], False
    for ln in head.splitlines():
        if ln.startswith("for var in (") or ln.startswith("from jwst_tool"):
            skip = True                      # env guard + tool imports
        if skip and ln.startswith("T_TRANSIT_S"):
            skip = False
        if skip:
            continue
        if (ln.startswith(("HERE =", "OUTPUTS =", "REPO ="))
                or "sys.path.insert" in ln):
            continue
        keep.append(ln)
    ns = {"np": np, "__name__": "parity_gate_probe"}
    exec(compile("\n".join(keep), str(PARITY), "exec"), ns)
    return ns


def _ok_row(key, ngroup=100, sat=0.5):
    return {
        "key": key, "status": "OK",
        "sat_frac_ours": sat,
        "npix_pandexo": 1000, "npix_matched": 1000,
        "ngroup_ours": ngroup, "ngroup_pandexo": ngroup,
        "config_ours": {"subarray": "sub", "readout": "RAPID",
                        "filter": "f", "disperser": "d"},
        "config_pandexo": {"subarray": "sub", "readout": "RAPID",
                           "filter": "f", "disperser": "d"},
        "flux_ratio": {"median": 1.001, "max_abs_dev": 0.02},
    }


@pytest.fixture
def passing(gate):
    """A minimal summary that satisfies every gate check."""
    rel = gate["REQUIRED_PANDEIA_RELEASE"]
    star = {
        "provenance_ours": {
            "worker_version": gate["PRODUCTION_WORKER_VERSION"],
            "engine_version": rel, "refdata_version": rel, "psf_version": rel,
        },
        "provenance_pandexo": {
            "pandeia_engine_version": rel, "refdata_version": rel,
            "psf_version": rel, "pandexo_version": "2026.7",
            "pandexo_commit": "34e42d81f782c8358bb30fc6e8cdf4b87e488263",
        },
        "modes": [_ok_row(k) for k in gate["REQUIRED_UNSATURATED_MODES"]],
    }
    return {"stars": {"w39_like": star}}


def test_a_clean_artifact_passes(gate, passing):
    assert gate["validate"](passing) == []


def test_worker_version_drift_fails(gate, passing):
    """The committed artifact's actual defect: generated by worker v5."""
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["provenance_ours"]["worker_version"] = 5
    problems = gate["validate"](s)
    assert any("worker_version=5" in p for p in problems), problems


def test_psf_version_mismatch_fails(gate, passing):
    """A mixed PSF release changes the PSF and so the extracted flux."""
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["provenance_pandexo"]["psf_version"] = "2026.2"
    problems = gate["validate"](s)
    assert any("psf release differs" in p for p in problems), problems


def test_unsupported_release_fails_even_when_both_sides_agree(gate, passing):
    """Two sides can agree with each other and still both be archival."""
    s = copy.deepcopy(passing)
    for side, keys in (("provenance_ours",
                        ("engine_version", "refdata_version", "psf_version")),
                       ("provenance_pandexo",
                        ("pandeia_engine_version", "refdata_version",
                         "psf_version"))):
        for k in keys:
            s["stars"]["w39_like"][side][k] = "2026.2"
    problems = gate["validate"](s)
    assert any("not the supported" in p for p in problems), problems


def test_missing_pandexo_commit_fails(gate, passing):
    """PandExo runs from master; a version string does not identify it."""
    s = copy.deepcopy(passing)
    del s["stars"]["w39_like"]["provenance_pandexo"]["pandexo_commit"]
    problems = gate["validate"](s)
    assert any("PandExo git commit" in p for p in problems), problems


def test_unknown_pandexo_version_fails(gate, passing):
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["provenance_pandexo"]["pandexo_version"] = "unknown"
    problems = gate["validate"](s)
    assert any("PandExo version is unknown" in p for p in problems), problems


def test_saturated_row_labeled_ok_fails(gate, passing):
    """The 2026-07 artifact carried two of these, one at 7.31x full well."""
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["modes"][0]["sat_frac_ours"] = 0.8548803964
    problems = gate["validate"](s)
    assert any("above the" in p and "limit" in p for p in problems), problems

    s["stars"]["w39_like"]["modes"][0]["sat_frac_ours"] = 7.3110978
    assert any("7.3111" in p for p in gate["validate"](s))


def test_error_row_fails(gate, passing):
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["modes"][0] = {
        "key": "nirspec_prism", "status": "ERROR", "ours_error": "boom"}
    problems = gate["validate"](s)
    assert any("error row" in p for p in problems), problems
    # ...and the mode it covered is now missing from the validated set
    assert any("no valid unsaturated comparison" in p for p in problems)


def test_missing_required_mode_fails(gate, passing):
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["modes"].pop()
    problems = gate["validate"](s)
    assert any("no valid unsaturated comparison" in p for p in problems), problems


def test_pixel_grid_mismatch_fails(gate, passing):
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["modes"][0]["npix_matched"] = 900     # 90%
    problems = gate["validate"](s)
    assert any("usable pixels matched" in p for p in problems), problems


def test_flux_ratio_drift_fails(gate, passing):
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["modes"][0]["flux_ratio"]["median"] = 1.05
    problems = gate["validate"](s)
    assert any("extracted-flux median ratio" in p for p in problems), problems


def test_config_mismatch_fails_but_an_implicit_default_does_not(gate, passing):
    """A real disagreement fails; an unset-because-derived key does not.

    Our registry omits `disperser` for MIRI LRS (the mode admits only the p750l
    prism and the engine derives it), while PandExo reports "p750l". That is a
    representation difference, not a configuration difference.
    """
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["modes"][0]["config_ours"]["disperser"] = None
    assert not [p for p in gate["validate"](s) if "disperser" in p]

    s["stars"]["w39_like"]["modes"][0]["config_ours"]["readout"] = "FASTR1"
    problems = gate["validate"](s)
    assert any("submitted readout differs" in p for p in problems), problems


def test_faint_star_group_rounding_is_allowed(gate, passing):
    """REPORT.md claims "~1% relative (up to 5 groups absolute)" on the faint
    star. At ngroup ~500 a 5-group rounding difference is 1.006%, so a pure 1%
    test would fail the real, matched artifact."""
    rel = gate["REQUIRED_PANDEIA_RELEASE"]
    star = copy.deepcopy(passing["stars"]["w39_like"])
    star["modes"] = [_ok_row(k) for k in gate["REQUIRED_UNSATURATED_MODES"]]
    star["modes"][0].update(ngroup_ours=497, ngroup_pandexo=492)   # 1.006%
    star["modes"][1].update(ngroup_ours=195, ngroup_pandexo=193)   # 1.03%
    s = {"stars": {"faint_k": star}}
    assert not [p for p in gate["validate"](s) if "ngroup" in p]

    # a real optimizer divergence still fails
    star["modes"][2].update(ngroup_ours=500, ngroup_pandexo=400)
    assert any("ngroup" in p for p in gate["validate"](s))


def test_bright_star_group_difference_of_two_fails(gate, passing):
    s = copy.deepcopy(passing)
    s["stars"]["w39_like"]["modes"][0].update(ngroup_ours=20,
                                              ngroup_pandexo=18)
    problems = gate["validate"](s)
    assert any("ngroup 20 vs 18" in p for p in problems), problems


def test_committed_artifact_does_not_pass_the_gate(gate):
    """Guard against the committed artifact being mistaken for a current pass.

    It must keep failing until it is regenerated on the supported release with
    worker v7. If this ever starts passing without a regeneration, something
    loosened the gate.
    """
    import json

    path = (PARITY.parents[1] / "outputs" / "parity_summary.json")
    if not path.is_file():                              # pragma: no cover
        pytest.skip("committed parity_summary.json not present")
    problems = gate["validate"](json.loads(path.read_text()))
    assert problems, "the stale 2026.2/worker-v5 artifact must not pass"
    joined = " ".join(problems)
    assert "worker_version=5" in joined
    assert "2026.2" in joined
